<?php
// This file is part of Moodle - https://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <https://www.gnu.org/licenses/>.

/**
 * Strings for tiny_zoomclassroom.
 *
 * @package     tiny_zoomclassroom
 * @copyright   2026
 * @license     http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

$string['pluginname'] = 'Zoom Classroom';
$string['settings'] = 'Zoom Classroom settings';
$string['privacy:metadata'] = 'The Zoom Classroom TinyMCE plugin stores launch metadata for embedded content but does not store personal data.';
$string['registrationpage'] = 'Dynamic registration';
$string['registrationpage_desc'] = 'Configure the Zoom Classroom TinyMCE integration here. Dynamic registration is required so the plugin can send its Moodle-owned OpenID, registration, and launch URLs to the tool.';
$string['registrationlinklabel'] = 'Open the dynamic registration flow';
$string['registrationurl'] = 'Dynamic registration URL';
$string['registrationurl_desc'] = 'Use the Zoom Classroom registration URL generated by the tool. The plugin does not store this URL; it uses it only to start Moodle-owned LTI dynamic registration.';
$string['registrationurlempty'] = 'Enter a dynamic registration URL before continuing.';
$string['registrationurlinvalid'] = 'Enter a valid HTTPS dynamic registration URL.';
$string['registrationstart'] = 'Start registration';
$string['registrationmodaltitle'] = 'Zoom Classroom dynamic registration';
$string['registrationclosebutton'] = 'Close';
$string['registrationdonebutton'] = 'Done and refresh';
$string['registrationrefreshnotice'] = 'When registration finishes, close this modal to refresh the configured tool details.';
$string['registrationworkflowheading'] = 'Run dynamic registration';
$string['registrationworkflowdesc'] = 'Start Zoom Classroom dynamic registration without leaving this page. If a Zoom Classroom tool is already configured, the plugin updates that same Moodle LTI registration instead of asking you to remap it manually.';
$string['registrationupdate'] = 'Update registration';
$string['registrationpreviewempty'] = 'No Zoom Classroom LTI 1.3 tool is configured yet. Run dynamic registration to create one.';
$string['registrationviewtools'] = 'View Moodle external tools';
$string['existingtoolpickerdesc'] = 'Or select an existing Moodle LTI 1.3 tool instead of running dynamic registration.';
$string['existingtoolpickerlabel'] = 'Existing Moodle tool';
$string['existingtoolpickerbutton'] = 'Use selected tool';
$string['existingtoolselected'] = 'Selected "{$a}" as the Zoom Classroom tool.';
$string['registrationdetected'] = 'Dynamic registration created and selected "{$a}" as the Zoom Classroom tool.';
$string['registrationcompletedcurrent'] = 'Dynamic registration completed. "{$a}" remains the configured Zoom Classroom tool.';
$string['moodleplatformheading'] = 'Moodle platform identity';
$string['moodleplatformheading_desc'] = 'Use Moodle core for LTI platform trust material and registration. {$a->registrationlink}<br><br>{$a->platformdetails}';
$string['moodleplatformregisterhelp'] = 'These are the platform values the tool should trust for the TinyMCE plugin registration and launch flow. The plugin owns the OpenID configuration, registration, and authorization endpoints while reusing Moodle issuer, token, and JWKS endpoints.';
$string['platformissuerlabel'] = 'Issuer: {$a}';
$string['platformopenidconfigurationlabel'] = 'OpenID configuration URL: {$a}';
$string['platformregistrationendpointlabel'] = 'Registration endpoint: {$a}';
$string['platformauthorizationendpointlabel'] = 'Authorization endpoint: {$a}';
$string['platformjwkslabel'] = 'JWKS URL: {$a}';
$string['toolid'] = 'Registered LTI tool';
$string['toolidnone'] = 'No eligible LTI 1.3 tools found';
$string['invalidtool'] = 'The configured external tool must support LTI 1.3 deep linking.';
$string['notconfigured'] = 'Not configured';
$string['unnamedtool'] = 'Unnamed external tool ({$a})';
$string['configuredtoolheading'] = 'Configured tool';
$string['configuredtooldesc'] = 'This is the Moodle LTI 1.3 tool currently configured for the Zoom Classroom TinyMCE button.';
$string['configuredtoollinklabel'] = 'Open Moodle tool';
$string['configuredtoolwithupdatedesc'] = 'This is the Moodle LTI 1.3 tool currently configured for the Zoom Classroom TinyMCE button. You can paste a new dynamic registration URL below to update or replace it.';
$string['configuredtoolclearbutton'] = 'Clear configured tool';
$string['configuredtooldeletebutton'] = 'Delete configured tool';
$string['configuredtoolclearconfirm'] = 'Clear the configured Zoom Classroom tool from this plugin?';
$string['configuredtooldeleteconfirm'] = 'Delete the configured Moodle external tool and clear it from this plugin?';
$string['configuredtoolcleared'] = 'The configured Zoom Classroom tool was cleared from the plugin.';
$string['configuredtooldeleted'] = 'The configured Moodle external tool was deleted and cleared from the plugin.';
$string['currenttoolheading'] = 'Configured Moodle tool';
$string['currenttooldesc'] = 'This is the Moodle LTI 1.3 tool registration the TinyMCE button currently uses. It is shown here as read-only because the plugin expects it to be created or updated through dynamic registration.';
$string['toolpreviewtoolid'] = 'Tool ID';
$string['toolpreviewname'] = 'Name';
$string['toolpreviewclientid'] = 'Client ID';
$string['toolpreviewdeploymentid'] = 'Deployment ID';
$string['toolpreviewtargetlinkuri'] = 'Target Link URI';
$string['toolpreviewdeeplinkuri'] = 'Deep Linking URI';
$string['toolpreviewloginuri'] = 'Initiate Login URL';
$string['toolpreviewjwksuri'] = 'JWKS URL';
$string['toolpreviewdescription'] = 'Description';
$string['advancedsettingsheading'] = 'Behavior settings';
$string['advancedsettingsdesc'] = 'These settings control how the TinyMCE button opens Zoom Classroom after registration is complete.';
$string['popupwidth'] = 'Popup width';
$string['popupwidth_desc'] = 'Width, in pixels, for the deep-linking popup window.';
$string['popupheight'] = 'Popup height';
$string['popupheight_desc'] = 'Height, in pixels, for the deep-linking popup window.';
$string['invalidpopupwidth'] = 'Popup width must be between 100 and 5000 pixels.';
$string['invalidpopupheight'] = 'Popup height must be between 100 and 5000 pixels.';
$string['advancedsettingssaved'] = 'Zoom Classroom behavior settings saved.';
$string['alloweddomains'] = 'Allowed launch domains';
$string['alloweddomains_desc'] = "Enter one domain pattern per line. Use `*.zoom.us` by default.";
$string['invalidalloweddomain'] = 'Invalid allowed domain pattern: {$a}';
$string['buttonlabel'] = 'Insert Zoom Classroom content';
$string['menuitem'] = 'Zoom Classroom';
$string['errormisconfigured'] = 'Zoom Classroom is not configured yet. Ask a Moodle administrator to map this button to a registered external tool.';
$string['errornocourse'] = 'Zoom Classroom can only be launched from a course context.';
$string['errorpopupblocked'] = 'The Zoom Classroom popup was blocked. Please allow popups for this site and try again.';
$string['insertfallbacktext'] = 'Open Zoom Classroom content';
$string['launchpage'] = 'Zoom Classroom';
$string['launchinstructions'] = 'Choose content in Zoom Classroom. When you finish, it will be inserted back into the editor.';
$string['launchfailed'] = 'Unable to start deep linking for the configured external tool.';
$string['invalidresponse'] = 'The LTI provider returned an invalid deep-linking response.';
$string['invalidlaunch'] = 'The Zoom Classroom launch request was invalid.';
$string['invalidtoolurl'] = 'The selected Zoom Classroom launch URL must use HTTPS and an approved Zoom host.';
$string['launchpreparing'] = 'Preparing Zoom Classroom launch...';
